In [31]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [25]:
data = '''1 1 8.0 9.7 1 1 5.7 8.7 1 1 8.7 4.7 1 2 8.0 3.6 1 2 4.2 8.7 1 2 8.0 8.8 1 3 8.0 9.5 1 3 4.7 8.6 1 3 8.7 4.7    
1 1 9.0 9.7 1 1 8.4 8.6 1 1 8.7 3.2 1 2 7.0 4.0 1 2 8.2 8.7 1 2 3.3 3.1 1 3 7.0 4.0 1 3 8.2 8.7 1 3 3.3 3.1      
1 1 7.0 9.4 1 1 8.7 5.2 1 1 7.4 8.4 1 2 8.0 9.5 1 2 4.5 8.6 1 2 8.7 4.7 1 3 6.2 9.7 1 3 5.7 8.7 1 3 8.7 4.7      
1 1 8.8 9.5 1 1 6.8 8.3 1 1 5.3 8.7 1 2 7.0 9.6 1 2 5.6 9.6 1 2 8.5 4.5 1 3 9.0 9.7 1 3 8.4 8.6 1 3 8.7 3.2      
1 1 8.8 9.5 1 1 5.7 8.3 1 1 4.3 8.0 1 2 6.0 4.1 1 2 8.6 7.1 1 2 5.1 8.6 1 3 7.0 4.0 1 3 8.2 8.7 1 3 3.3 4.1      
1 1 8.4 9.7 1 1 5.7 8.7 1 1 4.7 8.1 1 2 3.0 4.5 1 2 9.7 4.3 1 2 5.5 4.7 1 3 6.7 4.0 1 3 8.4 9.9 1 3 9.3 3.1      
2 1 9.0 9.7 2 1 3.4 8.2 2 1 8.7 3.2 2 2 8.8 9.5 2 2 5.3 8.7 2 2 5.7 8.3 2 3 6.0 4.1 2 3 5.1 8.6 2 3 9.7 4.3 
2 1 7.0 9.4 2 1 4.7 5.0 2 1 7.4 8.4 2 2 6.0 4.1 2 2 5.1 8.6 2 2 9.7 4.3 2 3 8.0 9.7 2 3 8.4 4.7 2 3 8.4 8.6 
2 1 8.0 9.5 2 1 5.7 8.6 2 1 5.7 4.7 2 2 7.0 4.0 2 2 3.7 3.1 2 2 8.4 8.6 2 3 7.0 4.0 2 3 3.3 3.1 2 3 8.4 8.6 
2 1 7.0 4.0 2 1 2.2 8.0 2 1 3.3 3.1 2 2 6.8 8.3 2 2 8.8 9.6 2 2 4.4 8.0 2 3 8.6 7.1 2 3 3.0 4.7 2 3 5.7 4.7
2 1 8.0 9.7 2 1 2.7 4.7 2 1 5.7 8.7 2 2 8.6 7.1 2 2 3.0 4.7 2 2 5.7 4.7 2 3 5.5 8.7 2 3 9.0 9.5 2 3 8.7 3.2
2 1 8.0 9.7 2 1 2.2 5.6 2 1 4.7 8.7 2 2 8.2 8.7 2 2 9.0 9.7 2 2 8.7 3.2 2 3 8.2 8.7 2 3 9.0 9.5 2 3 8.7 3.2'''

In [27]:
data = data.replace('\n',' ')
data = data.replace('       ',' ')
data

'1 1 8.0 9.7 1 1 5.7 8.7 1 1 8.7 4.7 1 2 8.0 3.6 1 2 4.2 8.7 1 2 8.0 8.8 1 3 8.0 9.5 1 3 4.7 8.6 1 3 8.7 4.7     1 1 9.0 9.7 1 1 8.4 8.6 1 1 8.7 3.2 1 2 7.0 4.0 1 2 8.2 8.7 1 2 3.3 3.1 1 3 7.0 4.0 1 3 8.2 8.7 1 3 3.3 3.1 1 1 7.0 9.4 1 1 8.7 5.2 1 1 7.4 8.4 1 2 8.0 9.5 1 2 4.5 8.6 1 2 8.7 4.7 1 3 6.2 9.7 1 3 5.7 8.7 1 3 8.7 4.7 1 1 8.8 9.5 1 1 6.8 8.3 1 1 5.3 8.7 1 2 7.0 9.6 1 2 5.6 9.6 1 2 8.5 4.5 1 3 9.0 9.7 1 3 8.4 8.6 1 3 8.7 3.2 1 1 8.8 9.5 1 1 5.7 8.3 1 1 4.3 8.0 1 2 6.0 4.1 1 2 8.6 7.1 1 2 5.1 8.6 1 3 7.0 4.0 1 3 8.2 8.7 1 3 3.3 4.1 1 1 8.4 9.7 1 1 5.7 8.7 1 1 4.7 8.1 1 2 3.0 4.5 1 2 9.7 4.3 1 2 5.5 4.7 1 3 6.7 4.0 1 3 8.4 9.9 1 3 9.3 3.1 2 1 9.0 9.7 2 1 3.4 8.2 2 1 8.7 3.2 2 2 8.8 9.5 2 2 5.3 8.7 2 2 5.7 8.3 2 3 6.0 4.1 2 3 5.1 8.6 2 3 9.7 4.3  2 1 7.0 9.4 2 1 4.7 5.0 2 1 7.4 8.4 2 2 6.0 4.1 2 2 5.1 8.6 2 2 9.7 4.3 2 3 8.0 9.7 2 3 8.4 4.7 2 3 8.4 8.6  2 1 8.0 9.5 2 1 5.7 8.6 2 1 5.7 4.7 2 2 7.0 4.0 2 2 3.7 3.1 2 2 8.4 8.6 2 3 7.0 4.0 2 3 3.3 3.1 2 3 8.4 8.6  2 1 7.0 4.0 2 1 2.2 8.0 2 1 3.3 3.1 2 2 6.8 8.3 2 2 8.8 9.6 2 2 4.4 8.0 2 3 8.6 7.1 2 3 3.0 4.7 2 3 5.7 4.7 2 1 8.0 9.7 2 1 2.7 4.7 2 1 5.7 8.7 2 2 8.6 7.1 2 2 3.0 4.7 2 2 5.7 4.7 2 3 5.5 8.7 2 3 9.0 9.5 2 3 8.7 3.2 2 1 8.0 9.7 2 1 2.2 5.6 2 1 4.7 8.7 2 2 8.2 8.7 2 2 9.0 9.7 2 2 8.7 3.2 2 3 8.2 8.7 2 3 9.0 9.5 2 3 8.7 3.2'

In [28]:
numbers = list(map(float, data.split()))
len(numbers)

432

In [30]:
reshaped = np.array(numbers).reshape(-1,4)
df = pd.DataFrame(reshaped, columns=['inputs', 'method', 'time', 'knowledge'])
df

     inputs  method  time  knowledge
0       1.0     1.0   8.0        9.7
1       1.0     1.0   5.7        8.7
2       1.0     1.0   8.7        4.7
3       1.0     2.0   8.0        3.6
4       1.0     2.0   4.2        8.7
..      ...     ...   ...        ...
103     2.0     2.0   9.0        9.7
104     2.0     2.0   8.7        3.2
105     2.0     3.0   8.2        8.7
106     2.0     3.0   9.0        9.5
107     2.0     3.0   8.7        3.2

[108 rows x 4 columns]

In [38]:
model = ols('knowledge ~ C(method)', data=df).fit()
anova_result = sm.stats.anova_lm(model, typ=2)

In [39]:
anova_result

               sum_sq     df         F    PR(>F)
C(method)   29.541296    2.0  2.525014  0.084909
Residual   614.221667  105.0       NaN       NaN