In [1]:
import pandas as pd
doc = pd.read_csv('c:/Temp/PANDASPLOTLY_FUNCODING_FULLDATA_20240601/00_Material(Uploaded)/COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv', encoding = 'utf-8-sig')
doc.tail(n=10)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
2512,NaN,NaN,NaN,"Korea, North",2020-04-01 21:58:49,40.3399,127.5101,0,0,0,0,"Korea, North"
2513,NaN,NaN,Unknown,Ukraine,2020-04-01 21:58:49,NaN,NaN,0,0,0,0,"Unknown, Ukraine"
2514,82601.0,NaN,England,United Kingdom,2020-04-01 21:58:49,52.3555,-1.1743,0,5430,0,0,"England, United Kingdom"
2515,82602.0,NaN,Northern Ireland,United Kingdom,2020-04-01 21:58:49,54.7877,-6.4923,0,59,0,0,"Northern Ireland, United Kingdom"
2516,82603.0,NaN,Scotland,United Kingdom,2020-04-01 21:58:49,56.4907,-4.2026,0,362,0,0,"Scotland, United Kingdom"
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.1307,-3.7837,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.5228,166.9315,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.0544,-169.8672,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.1095,177.6493,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.3768,-128.3242,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [2]:
doc.shape

(2522, 12)

In [3]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2522 entries, 0 to 2521
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIPS            2175 non-null   float64
 1   Admin2          2221 non-null   object
 2   Province_State  2338 non-null   object
 3   Country_Region  2522 non-null   object
 4   Last_Update     2522 non-null   object
 5   Lat             2518 non-null   float64
 6   Long_           2518 non-null   float64
 7   Confirmed       2522 non-null   int64
 8   Deaths          2522 non-null   int64
 9   Recovered       2522 non-null   int64
 10  Active          2522 non-null   int64
 11  Combined_Key    2522 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 236.6+ KB

In [4]:
doc.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key'],
      dtype='object')

In [5]:
doc.describe()

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,2175.000000,2518.000000,2518.000000,2522.000000,2522.000000,2522.000000,2522.000000
mean,30114.640920,35.289228,-75.615792,372.307296,20.477002,76.656622,278.524187
std,15643.080021,12.149460,47.809329,4174.952692,363.948042,1494.960160,2945.050096
min,1001.000000,-71.949900,-175.198200,0.000000,0.000000,0.000000,0.000000
25%,18052.000000,33.086811,-94.749118,2.000000,0.000000,0.000000,2.000000
50%,29031.000000,37.526763,-86.065254,7.000000,0.000000,0.000000,6.000000
75%,45024.000000,41.406878,-79.042655,34.000000,1.000000,0.000000,31.000000
max,99999.000000,71.706900,178.065000,110574.000000,13155.000000,63326.000000,80572.000000

In [6]:
doc.corr(numeric_only=True)

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
FIPS,1.000000,0.160717,0.171490,-0.000504,0.076467,NaN,0.002718
Lat,0.160717,1.000000,-0.476426,0.029389,0.026309,-0.002781,0.035631
Long_,0.171490,-0.476426,1.000000,0.141126,0.096924,0.141932,0.119737
Confirmed,-0.000504,0.029389,0.141126,1.000000,0.837153,0.727305,0.942484
Deaths,0.076467,0.026309,0.096924,0.837153,1.000000,0.546858,0.796549
Recovered,NaN,-0.002781,0.141932,0.727305,0.546858,1.000000,0.462484
Active,0.002718,0.035631,0.119737,0.942484,0.796549,0.462484,1.000000

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.figure(figsize=(5,5))

NameError: name 'figsize' is not defined