In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('project.xlsx')
data

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v25보호장비 미착용 사고 위험 노출,v26보도 주행 보행자 충돌 위험성,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
0,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,4,5,2,3,4,4,4,5,5
1,2,1,3,1.0,0.0,0,1.0,5.0,2.0,1.0,...,5,5,5,4,4,4,4,4,5,4
2,1,4,5,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,4,5,2,1,5,4,4,5,5
3,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
4,1,2,5,0.0,1.0,0,2.0,4.0,3.0,1.0,...,1,5,5,1,1,5,5,2,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,2,3,1,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
195,2,3,2,0.0,1.0,0,2.0,1.0,3.0,1.0,...,5,4,4,4,2,4,5,4,4,3
196,1,4,2,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
197,1,4,2,1.0,0.0,0,2.0,2.0,2.0,2.0,...,5,5,5,5,4,4,5,4,5,5
198,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5

In [4]:
data['v4이용종류'] = 0
data

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v26보도 주행 보행자 충돌 위험성,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류
0,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,4,5,2,3,4,4,4,5,5,0
1,2,1,3,1.0,0.0,0,1.0,5.0,2.0,1.0,...,5,5,4,4,4,4,4,5,4,0
2,1,4,5,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,5,2,1,5,4,4,5,5,0
3,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,0
4,1,2,5,0.0,1.0,0,2.0,4.0,3.0,1.0,...,5,5,1,1,5,5,2,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,2,3,1,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,0
195,2,3,2,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,4,4,2,4,5,4,4,3,0
196,1,4,2,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,0
197,1,4,2,1.0,0.0,0,2.0,2.0,2.0,2.0,...,5,5,5,4,4,5,4,5,5,0
198,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,0

In [ ]:
def v4(row):
    if row['v41이용종류'] ==1.0 :
        return 1
    if row['v42이용종류'] ==1.0 :
        return 2
    if row['v43이용종류'] ==1.0 :
        return 3

In [7]:
data['v4이용종류'] = data.apply(v4, axis=1)

In [11]:
data.drop(columns=['v41이용종류','v42이용종류','v43이용종류'], inplace=True)
data

,v1성별,v2학년,v3소속대학,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,v9보험가입여부,v10음주여부,v11사고경험,...,v26보도 주행 보행자 충돌 위험성,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류
0,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,5,2,3,4,4,4,5,5,3
1,2,1,3,1.0,5.0,2.0,1.0,3.0,1.0,1.0,...,5,5,4,4,4,4,4,5,4,1
2,1,4,5,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,4,5,2,1,5,4,4,5,5,2
3,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,3
4,1,2,5,2.0,4.0,3.0,1.0,2.0,1.0,1.0,...,5,5,1,1,5,5,2,5,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,2,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,3
195,2,3,2,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,4,4,4,2,4,5,4,4,3,2
196,1,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,3
197,1,4,2,2.0,2.0,2.0,2.0,2.0,1.0,1.0,...,5,5,5,4,4,5,4,5,5,1
198,2,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,5,1,5,5,5,5,5,3